environment:
  matrix:
    - job_name: Windows MinGW builds
      appveyor_build_worker_image: Visual Studio 2015
        
    - job_name: Windows VS 2019 builds
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: MacOS builds
      appveyor_build_worker_image: macos-bigsur

    - job_name: Ubuntu Linux builds
      appveyor_build_worker_image: Ubuntu2004

for:
-
  matrix:
    only:
      - job_name: Windows MinGW builds

  install:
  - choco install vulkan-sdk
  - refreshenv
  - set SELECTED_MINGW=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0
  - set PATH=%PATH%;%SELECTED_MINGW%\mingw64\bin
  - rmdir /Q /S C:\msys64
  - rmdir /Q /S C:\MinGW
  - del "C:\Program Files\Git\usr\bin\sh.exe"
  
  test_script:
  - .\build-all-mingw.bat Debug
  - git clean -fdx
  - rmdir /Q /S small3d
  - .\build-all-mingw.bat Release
  - git clean -fdx
  - rmdir /Q /S small3d
  - .\build-all-mingw.bat Debug opengl
  - git clean -fdx
  - rmdir /Q /S small3d
  - .\build-all-mingw.bat Release opengl
-
  matrix:
    only:
      - job_name: Windows VS 2019 builds

  install:
  - choco install vulkan-sdk
  - refreshenv
  
  test_script:
  - .\build-all-vs.bat Debug
  - git clean -fdx
  - rmdir /Q /S small3d
  - .\build-all-vs.bat Release
  - git clean -fdx
  - rmdir /Q /S small3d
  - .\build-all-vs.bat Debug opengl
  - git clean -fdx
  - rmdir /Q /S small3d
  - .\build-all-vs.bat Release opengl
-
  matrix:
    only:
      - job_name: MacOS builds
        
  test_script:
  - ./build-all.sh Debug opengl
  - git clean -fdx
  - rm -rf small3d
  - ./build-all.sh Release opengl
-
  matrix:
    only:
      - job_name: Ubuntu Linux builds
  
  test_script:
  - ./build-all.sh Debug 
  - git clean -fdx
  - rm -rf small3d
  - ./build-all.sh Release 
  - git clean -fdx
  - rm -rf small3d
  - ./build-all.sh Debug opengl
  - git clean -fdx
  - rm -rf small3d
  - ./build-all.sh Release opengl

build: off
